language: python

python:
  - 2.7
  - 3.4
  - 3.6

cache: pip

virtualenv:
    system_site_package: true

services:
 - mysql

install:
 - pip install -r requirements-dev.txt

script:
 - sh .travis.sh

notifications:
  email:
    - konstantin@linuxfoundation.org
